name = "ecochaser"
compatibility_date = "2025-11-24"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "eco-chaser_db"
database_id = "879b05fc-ba01-4ce5-9cf3-d8c9f7221dbc"

[env.dev.d1_databases]
binding = "DB"
database_name = "eco-chaser_db"
database_id = "879b05fc-ba01-4ce5-9cf3-d8c9f7221dbc"